name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: espressif/idf:release-v5.0
    steps:
      - uses: actions/checkout@v3
      - name: Build firmware
        run: idf.py build
      - name: Build unit tests
        run: idf.py -C tests build
